import sqlite3
conn = sqlite3.connect('singleminded.db')
c = conn.cursor()
c.execute("DROP TABLE IF EXISTS tasks")
c.execute("CREATE TABLE tasks (taskid, userid, title, description, timestamp, deadline, priority, effort, ordinality)")
c.execute("INSERT INTO tasks VALUES (0, 0, 'buy milk', '', '9-28-13', '9-29-13', 1, 2, 0)")
c.execute("SELECT * FROM tasks")
print(c.fetchall())
conn.commit()
conn.close()
